---
apiVersion: v1
kind: Service
metadata:
  name: kad
spec:
  selector:
    app: kad
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kad
data:
  config.yml: |
    abc: 123
    password: LinuxDays
  option.color: red
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  username: YWRtaW4=
  password: TGludXhEYXlz
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kad
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
      - name: app
        image: tomkukral/kad
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["/bin/kad", "--color", "$(COLOR)", "--user", "$(USERNAME)"]
        env:
        # static configuration from yaml
        - name: REDIS_SERVER
          value: redis-0.redis:6379
        # configuraiton from downward API
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # variable form configmap
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: kad
              key: option.color
        # variables from secret
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
        volumeMounts:
        - name: config
          mountPath: /etc/kad/
      volumes:
      - name: config
        configMap:
          name: kad
          items:
          - key: config.yml
            path: config.yml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: 128Mi
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: redis-disk
  volumeClaimTemplates:
  - metadata:
      name: redis-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
